INSERT INTO [OrderingSystemDB].[dbo].[Countries] ([ID]
      ,[continent]
      ,[countryAbr]
      ,[countryName]
      ,[latitude]
      ,[localName]
      ,[longitude]
      ,[population]
      ,[region]
      ,[surfaceArea]
      ,[webCode])
SELECT [ID]
      ,[continent]
      ,[countryAbr]
      ,[countryName]
      ,[latitude]
      ,[localName]
      ,[longitude]
      ,[population]
      ,[region]
      ,[surfaceArea]
      ,[webCode] FROM [OrderingSystem].[dbo].[Countries];